name: whatsapp-for-linux
base: core18
summary: Unofficial WhatsApp client
description: An unofficial WhatsApp desktop application for linux
grade: stable
confinement: strict
adopt-info: whatsapp-for-linux

parts:
  whatsapp-for-linux:
    source-type: local
    source: .
    plugin: cmake
    override-pull: |
      snapcraftctl pull
      sed -i.bak -e 's|Icon=whatsapp-for-linux|Icon=share/icons/hicolor/256x256/apps/whatsapp-for-linux.png|g' resource/desktop/whatsapp-for-linux.desktop
      version=$(cat "src/VERSION")
      echo "Setting version to ${version}"
      snapcraftctl set-version $version
    configflags:
      - -DCMAKE_BUILD_TYPE=Release
    build-packages:
      - build-essential
      - libgtkmm-3.0-dev
      - libwebkit2gtk-4.0-dev
      - libappindicator3-dev
    stage-packages:
      - libgtkmm-3.0-1v5
      - libappindicator3-1
      - gstreamer1.0-plugins-base
      - gstreamer1.0-plugins-good
      - gstreamer1.0-plugins-bad
      - gstreamer1.0-libav

slots:
  dbus-app:
    interface: dbus
    bus: session
    name: com.github.whatsapp-for-linux

apps:
  whatsapp-for-linux:
    command: bin/whatsapp-for-linux
    desktop: share/applications/whatsapp-for-linux.desktop
    common-id: com.github.whatsapp-for-linux
    extensions: [gnome-3-28]  # This takes care of most of the things for us
    plugs:
      - network
      - network-manager
      - network-manager-observe
      - browser-support
      - camera
      - audio-playback
      - audio-record
      - home
      - removable-media
      - opengl
      - upower-observe
      - screen-inhibit-control
    slots:
      - dbus-app
