name: whatsapp-for-linux
base: core18
version: '1.0.6'
summary: An unofficial WhatsApp linux client.
description: An unofficial WhatsApp linux client written in C++ with the help of gtkmm-3.0 and webkit2.
grade: stable
confinement: strict

parts:
  whatsapp-for-linux:
    source-type: git
    source-branch: master
    source: https://github.com/eneshecan/whatsapp-for-linux
    plugin: cmake
    override-pull: |
      snapcraftctl pull
      sed -i.bak -e 's|Icon=whatsapp-for-linux|Icon=share/icons/hicolor/256x256/apps/whatsapp-for-linux.png|g' resource/desktop/whatsapp-for-linux.desktop
    configflags:
      - -DCMAKE_BUILD_TYPE=Release
    build-packages:
      - g++
      - cmake
      - make
      - libgtkmm-3.0-dev
      - libwebkit2gtk-4.0-dev
    stage-packages:
      - libgtkmm-3.0-1v5

slots:
  dbus-app:
    interface: dbus
    bus: session
    name: com.github.whatsapp-for-linux

apps:
  whatsapp-for-linux:
    command: desktop-launch whatsapp-for-linux
    desktop: share/applications/whatsapp-for-linux.desktop
    common-id: com.github.whatsapp-for-linux
    extensions: [gnome-3-28] # This takes care of most of the things for us
    plugs:
      - network
      - network-manager
      - browser-support
      - camera
      - audio-playback
      - audio-record
      - home
      - opengl
      - upower-observe
    slots:
      - dbus-app
